spring:
  cloud:
    gateway:
      routes:
        # 库存服务网关拦截
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters: # 路径重写
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        # 第三方服务网关拦截
        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters: # 路径重写
            - RewritePath=/api/thirdparty(?<segment>/?.*), /$\{segment}

        # 商品服务网关拦截
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters: # 路径重写
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        # 商品服务网关拦截
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters: # 路径重写
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        # 管理服务网关拦截
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          #前端项目都加上/api
          filters: # 路径重写
            - RewritePath=/api(?<segment>/?.*), /renren-fast/$\{segment}


