spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t6McHdFv4UQHjx7R8ZG
      secret-key: b7GJznsO7kksmZzYWuqWbcGKpcYISw
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: stone-mall-oss

  application:
    name: mall-third-party

server:
  port: 30000
